Covenant/Models/Grunts/GruntTask.cs
// Author: Ryan Cobb (@cobbr_io)
// Project: Covenant (https://github.com/cobbr/Covenant)
// License: GNU GPLv3

using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

using Newtonsoft.Json;
using Microsoft.CodeAnalysis;

using Covenant.Core;

namespace Covenant.Models.Grunts
{
    public class GruntTaskOption
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
        public string DefaultValue { get; set; }
        public string Description { get; set; }
        public List<string> SuggestedValues { get; set; } = new List<string>();
        public bool Optional { get; set; } = false;
        public bool DisplayInCommand { get; set; } = true;
        
        public int GruntTaskId { get; set; }
        public GruntTask Task { get; set; }
    }

    public class GruntTask
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; } = "GenericTask";
        public List<string> AlternateNames { get; set; } = new List<string>();
        public string Description { get; set; } = "A generic GruntTask.";
        public string Help { get; set; }
        public ImplantLanguage Language { get; set; } = ImplantLanguage.CSharp;

        public string Code { get; set; } = "";
        public GruntTaskingType TaskingType { get; set; } = GruntTaskingType.Assembly;
        public bool Compiled { get; set; } = false;
        public bool UnsafeCompile { get; set; } = false;
        public bool TokenTask { get; set; } = false;

        public List<GruntTaskOption> Options { get; set; } = new List<GruntTaskOption>();

        private List<GruntTaskReferenceSourceLibrary> GruntTaskReferenceSourceLibraries { get; set; } = new List<GruntTaskReferenceSourceLibrary>();
        private List<GruntTaskReferenceAssembly> GruntTaskReferenceAssemblies { get; set; } = new List<GruntTaskReferenceAssembly>();
        private List<GruntTaskEmbeddedResource> GruntTaskEmbeddedResources { get; set; } = new List<GruntTaskEmbeddedResource>();
        [NotMapped]
        public List<ReferenceSourceLibrary> ReferenceSourceLibraries => GruntTaskReferenceSourceLibraries.Select(e => e.ReferenceSourceLibrary).ToList();
        [NotMapped]
        public List<ReferenceAssembly> ReferenceAssemblies => GruntTaskReferenceAssemblies.Select(e => e.ReferenceAssembly).ToList();
        [NotMapped]
        public List<EmbeddedResource> EmbeddedResources => GruntTaskEmbeddedResources.Select(e => e.EmbeddedResource).ToList();

        public void Add(ReferenceSourceLibrary library)
        {
            GruntTaskReferenceSourceLibraries.Add(new GruntTaskReferenceSourceLibrary
            {
                GruntTaskId = this.Id, GruntTask = this,
                ReferenceSourceLibraryId = library.Id, ReferenceSourceLibrary = library
            });
        }

        public void Remove(ReferenceSourceLibrary library)
        {
            GruntTaskReferenceSourceLibraries.Remove(
                GruntTaskReferenceSourceLibraries
                    .FirstOrDefault(GTRSL => GTRSL.GruntTaskId == this.Id && GTRSL.ReferenceSourceLibraryId == library.Id)
            );
        }

        public void Add(ReferenceAssembly assembly)
        {
            GruntTaskReferenceAssemblies.Add(new GruntTaskReferenceAssembly
            {
                GruntTaskId = this.Id, GruntTask = this,
                ReferenceAssemblyId = assembly.Id, ReferenceAssembly = assembly
            });
        }

        public void Remove(ReferenceAssembly assembly)
        {
            GruntTaskReferenceAssemblies.Remove(
                GruntTaskReferenceAssemblies
                    .FirstOrDefault(GTRA => GTRA.GruntTaskId == this.Id && GTRA.ReferenceAssemblyId == assembly.Id)
            );
        }

        public void Add(EmbeddedResource resource)
        {
            GruntTaskEmbeddedResources.Add(new GruntTaskEmbeddedResource
            {
                GruntTaskId = this.Id, GruntTask = this,
                EmbeddedResourceId = resource.Id, EmbeddedResource = resource
            });
        }

        public void Remove(EmbeddedResource resource)
        {
            GruntTaskEmbeddedResources.Remove(
                GruntTaskEmbeddedResources
                    .FirstOrDefault(GTER => GTER.GruntTaskId == this.Id && GTER.EmbeddedResourceId == resource.Id)
            );
        }

        public byte[] GetCompressedILAssembly35()
        {
            return File.ReadAllBytes(Common.CovenantTaskCSharpCompiledNet35Directory + this.Name + ".compiled");
        }

        public byte[] GetCompressedILAssembly40()
        {
            return File.ReadAllBytes(Common.CovenantTaskCSharpCompiledNet40Directory + this.Name + ".compiled");
        }

        public void Compile()
        {
            if (!this.Compiled)
            {
                List<Compiler.EmbeddedResource> resources = this.EmbeddedResources.Select(ER =>
                {
                    return new Compiler.EmbeddedResource
                    {
                        Name = ER.Name,
                        File = ER.Location,
                        Platform = Platform.X64,
                        Enabled = true
                    };
                }).ToList();
                this.ReferenceSourceLibraries.ToList().ForEach(RSL =>
                {
                    resources.AddRange(
                        RSL.EmbeddedResources.Select(ER =>
                        {
                            return new Compiler.EmbeddedResource
                            {
                                Name = ER.Name,
                                File = ER.Location,
                                Platform = Platform.X64,
                                Enabled = true
                            };
                        })
                    );
                });
                List<Compiler.Reference> references35 = new List<Compiler.Reference>();
                this.ReferenceSourceLibraries.ToList().ForEach(RSL =>
                {
                    references35.AddRange(
                        RSL.ReferenceAssemblies.Where(RA => RA.DotNetVersion == Common.DotNetVersion.Net35).Select(RA =>
                        {
                            return new Compiler.Reference { File = RA.Location, Framework = Common.DotNetVersion.Net35, Enabled = true };
                        })
                    );
                });
                references35.AddRange(
                    this.ReferenceAssemblies.Where(RA => RA.DotNetVersion == Common.DotNetVersion.Net35).Select(RA =>
                    {
                        return new Compiler.Reference { File = RA.Location, Framework = Common.DotNetVersion.Net35, Enabled = true };
                    })
                );

                File.WriteAllBytes(Common.CovenantTaskCSharpCompiledNet35Directory + this.Name + ".compiled",
                    Utilities.Compress(Compiler.Compile(new Compiler.CompilationRequest
                    {
                        Source = this.Code,
                        SourceDirectories = this.ReferenceSourceLibraries.Select(RSL => RSL.Location).ToList(),
                        TargetDotNetVersion = Common.DotNetVersion.Net35,
                        References = references35,
                        EmbeddedResources = resources,
                        UnsafeCompile = this.UnsafeCompile,
                        Confuse = true,
                        // TODO: Fix optimization to work with GhostPack
                        Optimize = !this.ReferenceSourceLibraries.Select(RSL => RSL.Name).Contains("Rubeus") &&
                               !this.ReferenceSourceLibraries.Select(RSL => RSL.Name).Contains("Seatbelt") &&
                               !this.ReferenceSourceLibraries.Select(RSL => RSL.Name).Contains("SharpDPAPI") &&
                               !this.ReferenceSourceLibraries.Select(RSL => RSL.Name).Contains("SharpDump") &&
                               !this.ReferenceSourceLibraries.Select(RSL => RSL.Name).Contains("SharpUp") &&
                               !this.ReferenceSourceLibraries.Select(RSL => RSL.Name).Contains("SharpWMI")
                    }))
                );
                List<Compiler.Reference> references40 = new List<Compiler.Reference>();
                this.ReferenceSourceLibraries.ToList().ForEach(RSL =>
                {
                    references40.AddRange(
                        RSL.ReferenceAssemblies.Where(RA => RA.DotNetVersion == Common.DotNetVersion.Net40).Select(RA =>
                        {
                            return new Compiler.Reference { File = RA.Location, Framework = Common.DotNetVersion.Net40, Enabled = true };
                        })
                    );
                });
                references40.AddRange(
                    this.ReferenceAssemblies.Where(RA => RA.DotNetVersion == Common.DotNetVersion.Net40).Select(RA =>
                    {
                        return new Compiler.Reference { File = RA.Location, Framework = Common.DotNetVersion.Net40, Enabled = true };
                    })
                );
                File.WriteAllBytes(Common.CovenantTaskCSharpCompiledNet40Directory + this.Name + ".compiled",
                    Utilities.Compress(Compiler.Compile(new Compiler.CompilationRequest
                    {
                        Source = this.Code,
                        SourceDirectories = this.ReferenceSourceLibraries.Select(RSL => RSL.Location).ToList(),
                        TargetDotNetVersion = Common.DotNetVersion.Net40,
                        References = references40,

Covenant/Controllers/ViewControllers/GruntTaskController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Collections.Generic;

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;

using Covenant.Core;
using Covenant.Models;
using Covenant.Models.Grunts;

namespace Covenant.Controllers
{
    [Authorize]
    public class GruntTaskController : Controller
    {
        private readonly CovenantContext _context;

        public GruntTaskController(CovenantContext context)
        {
            _context = context;
        }

        // GET: /grunttask
        public async Task<IActionResult> Index()
        {
            ViewBag.ReferenceSourceLibraries = await _context.GetReferenceSourceLibraries();
            ViewBag.ReferenceAssemblies = await _context.GetReferenceAssemblies();
            ViewBag.EmbeddedResources = await _context.GetEmbeddedResources();
            return View(await _context.GetGruntTasks());
        }

        // GET: /grunttask/edit/{id}
        public async Task<IActionResult> Edit(int id)
        {
            try
            {
                ViewBag.ReferenceSourceLibraries = await _context.GetReferenceSourceLibraries();
                ViewBag.ReferenceAssemblies = await _context.GetReferenceAssemblies();
                ViewBag.EmbeddedResources = await _context.GetEmbeddedResources();
                return View(await _context.GetGruntTask(id));
            }
            catch (Exception e) when (e is ControllerNotFoundException || e is ControllerBadRequestException || e is ControllerUnauthorizedException)
            {
                return RedirectToAction(nameof(Index));
            }
        }

        public class GruntTaskModel : GruntTask
        {
            public new List<int> ReferenceAssemblies { get; set; } = new List<int>();
            public new List<int> EmbeddedResources { get; set; } = new List<int>();
            public new List<int> ReferenceSourceLibraries { get; set; } = new List<int>();
        }

        // POST: /grunttask/edit
        [HttpPost]
        public async Task<IActionResult> Edit(GruntTaskModel taskModel)
        {
            try
            {
                GruntTask task = new GruntTask
                {
                    Id = taskModel.Id,
                    Name = taskModel.Name,
                    Description = taskModel.Description,
                    Help = taskModel.Help,
                    Code = taskModel.Code,
                    UnsafeCompile = taskModel.UnsafeCompile,
                    TokenTask = taskModel.TokenTask,
                    Options = taskModel.Options
                };
                taskModel.ReferenceSourceLibraries.ForEach(async RSL => {
                    task.Add(await _context.GetReferenceSourceLibrary(RSL));
                });
                taskModel.ReferenceAssemblies.ForEach(async RA => {
                    task.Add(await _context.GetReferenceAssembly(RA));
                });
                taskModel.EmbeddedResources.ForEach(async ER => {
                    task.Add(await _context.GetEmbeddedResource(ER));
                });
                ViewBag.ReferenceSourceLibraries = await _context.GetReferenceSourceLibraries();
                ViewBag.ReferenceAssemblies = await _context.GetReferenceAssemblies();
                ViewBag.EmbeddedResources = await _context.GetEmbeddedResources();
                return View(await _context.EditGruntTask(task));
            }
            catch (Exception e) when (e is ControllerNotFoundException || e is ControllerBadRequestException || e is ControllerUnauthorizedException)
            {
                return RedirectToAction(nameof(Edit), new { Id = taskModel.Id });
            }
        }

        // GET: /grunttask/create
        public async Task<IActionResult> Create()
        {
            try
            {
                ViewBag.ReferenceSourceLibraries = await _context.GetReferenceSourceLibraries();
                ViewBag.ReferenceAssemblies = await _context.GetReferenceAssemblies();
                ViewBag.EmbeddedResources = await _context.GetEmbeddedResources();
                return View(new GruntTask());
            }
            catch (Exception e) when (e is ControllerNotFoundException || e is ControllerBadRequestException || e is ControllerUnauthorizedException)
            {
                return RedirectToAction(nameof(Index));
            }
        }

        // POST: /grunttask/create
        [HttpPost]
        public async Task<IActionResult> Create(GruntTaskModel taskModel)
        {
            try
            {
                GruntTask task = new GruntTask
                {
                    Name = taskModel.Name,
                    Description = taskModel.Description,
                    Help = taskModel.Help,
                    Code = taskModel.Code,
                    UnsafeCompile = taskModel.UnsafeCompile,
                    TokenTask = taskModel.TokenTask,
                    Options = taskModel.Options
                };
                taskModel.ReferenceSourceLibraries.ForEach(async RSL => {
                    task.Add(await _context.GetReferenceSourceLibrary(RSL));
                });
                taskModel.ReferenceAssemblies.ForEach(async RA => {
                    task.Add(await _context.GetReferenceAssembly(RA));
                });
                taskModel.EmbeddedResources.ForEach(async ER => {
                    task.Add(await _context.GetEmbeddedResource(ER));
                });
                ViewBag.ReferenceSourceLibraries = await _context.GetReferenceSourceLibraries();
                ViewBag.ReferenceAssemblies = await _context.GetReferenceAssemblies();
                ViewBag.EmbeddedResources = await _context.GetEmbeddedResources();
                GruntTask createdTask = await _context.CreateGruntTask(task);
                return RedirectToAction(nameof(Edit), new { Id = createdTask.Id });
            }
            catch (Exception e) when (e is ControllerNotFoundException || e is ControllerBadRequestException || e is ControllerUnauthorizedException)
            {
                ViewBag.ReferenceSourceLibraries = await _context.GetReferenceSourceLibraries();
                ViewBag.ReferenceAssemblies = await _context.GetReferenceAssemblies();
                ViewBag.EmbeddedResources = await _context.GetEmbeddedResources();
                return View(new GruntTask());
            }
        }
    }
}

Covenant/Views/GruntTask/Create.cshtml
@using Covenant.Models.Grunts
@model GruntTask
@{
    Layout = "_GruntTaskLayout";
    ViewData["Title"] = "GruntTasks";
    IEnumerable<ReferenceSourceLibrary> ReferenceSourceLibraries = ViewBag.ReferenceSourceLibraries;
    IEnumerable<ReferenceAssembly> ReferenceAssemblies = ViewBag.ReferenceAssemblies;
    IEnumerable<EmbeddedResource> EmbeddedResources = ViewBag.EmbeddedResources;
    IEnumerable<SelectListItem> librarySelectList = ReferenceSourceLibraries.Select(RSL =>
    {
        return new SelectListItem { Text = RSL.Name, Value = RSL.Id.ToString(), Selected = false };
    });
    IEnumerable<SelectListItem> assemblySelectList = ReferenceAssemblies.Select(RA =>
    {
        return new SelectListItem { Text = RA.Name, Value = RA.Id.ToString(), Selected = false };
    });
    IEnumerable<SelectListItem> resourceSelectList = EmbeddedResources.Select(ER =>
    {
        return new SelectListItem { Text = ER.Name, Value = ER.Id.ToString(), Selected = false };
    });
}
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap pb-2 mb-3">
    <h1 class="h2">Create GruntTask</h1>
</div>

<form id="edit-task-form" asp-action="Create">
    <input asp-for="Id" type="hidden">
    <div class="form-row">
        <div class="form-group col-md-4">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control">
        </div>
        <div class="form-group col-md-8">
            <label asp-for="Description"></label>
            <input asp-for="Description" class="form-control">
        </div>
    </div>
    <div class="form-check form-check-inline">
        <input id="TokenTask" name="TokenTask" class="form-check-input" type="checkbox">
        <label id="TokenTask" name="TokenTask" class="form-check-label">TokenTask</label>
    </div>
    <div class="form-check form-check-inline">
        <input id="UnsafeCompile" name="UnsafeCompile" class="form-check-input" type="checkbox">
        <label id="UnsafeCompile" name="UnsafeCompile" class="form-check-label">UnsafeCompile</label>
    </div>
    <div class="form-row">
        <div class="form-group">
            <label asp-for="ReferenceSourceLibraries"></label><br />
            <select asp-for="ReferenceSourceLibraries" class="selectpicker show-menu-arrow" multiple data-dropup-auto="false" data-width="auto" data-live-search="true" data-selected-text-format="count > 2">
                @foreach (var library in librarySelectList)
                {
                    <option value="@library.Value">@library.Text</option>
                }
            </select>
        </div>
    </div>
    <div class="form-row">
        <div class="form-group">
            <label asp-for="ReferenceAssemblies"></label><br />
            <select asp-for="ReferenceAssemblies" class="selectpicker show-menu-arrow" multiple data-dropup-auto="false" data-width="auto" data-live-search="true" data-selected-text-format="count > 2">
                @foreach (var assembly in assemblySelectList)
                {
                    <option value="@assembly.Value">@assembly.Text</option>
                }
            </select>
        </div>
    </div>
    <div class="form-row">
        <div class="form-group">
            <label asp-for="EmbeddedResources"></label><br />
            <select asp-for="EmbeddedResources" class="selectpicker show-menu-arrow" multiple data-dropup-auto="false" data-width="auto" data-live-search="true" data-selected-text-format="count > 2">
                @foreach (var resource in resourceSelectList)
                {
                    <option value="@resource.Value">@resource.Text</option>
                }
            </select>
        </div>
    </div>

    <h5>Options</h5>
    @for (int i = 0; i < Model.Options.Count; i++)
    {
        <div class="form-row option-row mt-2">
            <input asp-for="Options[i].Id" value="@Model.Options[i].Id" class="form-control" type="hidden" readonly>
            <input asp-for="Options[i].GruntTaskId" value="@Model.Id" class="form-control" type="hidden" readonly>
            <input asp-for="Options[i].Value" value="@Model.Options[i].Value" class="form-control" type="hidden">
            <div class="col-md-4">
                <div class="row">
                    <div class="form-group col-auto">
                        <label asp-for="Options[i].Name"><b>@i</b>. Name</label>
                        <input asp-for="Options[i].Name" value="@Model.Options[i].Name" class="form-control">
                    </div>
                    <div class="form-check form-check-inline mt-2">
                        @{
                            var id = "Options_" + i + "__Optional";
                            var name = "Options[" + i + "].Optional";
                        }
                        <input id="@id" name="@name" class="form-check-input" type="checkbox">
                        <label for="@id" class="form-check-label">Optional</label>
                    </div>
                </div>
                <div class="row form-group col-auto">
                    <label asp-for="Options[i].Description"></label>
                    <input asp-for="Options[i].Description" value="@Model.Options[i].Description" class="form-control">
                </div>
            </div>
            <div class="col-auto align-self-center">
                <button type="button" class="btn btn-outline-danger btn-sm xbutton remove-option-button">
                    <span data-feather="x"></span>
                </button>
            </div>
        </div>
    }
    <button type="button" id="add-option-button" class="btn btn-outline-primary btn-sm mb-4"><span data-feather="plus"></span> Add</button>
    <div class="form-group">
        <label asp-for="Help"></label>
        <textarea asp-for="Help" rows="10" class="form-control"></textarea>
    </div>
    <div class="form-group">
        <label asp-for="Code"></label>
        <textarea asp-for="Code" rows="20" class="form-control"></textarea>
    </div>
    <button id="edit-task-submit" type="button" class="btn btn-primary"><span data-feather="plus"></span> Create</button>
</form>

@section Scripts {
<script type="text/javascript">
    $(document).ready(function () {
        var editor = CodeMirror.fromTextArea(document.getElementById("Code"), {
            lineNumbers: true,
            mode: "text/x-csharp"
        });

        $("#edit-task-submit").click(function () {
            $(".form-check-input").each(function () {
                if ($(this).is(":checked")) {
                    $(this).val("True");
                }
                else {
                    $(this).prop("checked", true);
                    $(this).val("False");
                }
            });
            $("#edit-task-form").submit();
        });

        var addOption = function () {
            var num = $(".option-row").length;
            var modelId = $("form > input#Id").val();
            var newitem = '<div class="form-row option-row mt-2">' +
                '    <input id="Options_' + num + '__Id" name="Options[' + num + '].Id" value="0" class="form-control" type="hidden" readonly>' +
                '    <input id="Options_' + num + '__GruntTaskId" name="Options[' + num + '].GruntTaskId" value="' + modelId + '" class="form-control" type="hidden" readonly>' +
                '    <input id="Options_' + num + '__Value" name="Options[' + num + '].Value" class="form-control" type="hidden">' +
                '    <div class="col-md-4">' +
                '        <div class="row">' +
                '            <div class="form-group col-auto">' +
                '                <label for="Options_' + num + '__Name"><b>' + num + '</b>. Name</label>' +
                '                <input id="Options_' + num + '__Name" name="Options[' + num + '].Name" class="form-control">' +
                '            </div>' +
                '            <div class="form-check form-check-inline mt-2">' +
                '                <input id="Options_' + num + '__Optional" name="Options[' + num + '].Optional" value="False" data-val="true" class="form-check-input" type="checkbox">' +
                '                <label for="Options_' + num + '__Optional" class="form-check-label">Optional</label>' +
                '            </div>' +
                '        </div>' +
                '        <div class="row form-group col-auto">' +
                '            <label for="Options_' + num + '__Description">Description</label>' +
                '            <input id="Options_' + num + '__Description" name="Options[' + num + '].Description" class="form-control">' +
                '        </div>' +
                '    </div>' +
                '    <div class="col-auto align-self-center">' +
                '        <button type="button" class="btn btn-outline-danger btn-sm xbutton remove-option-button"><span data-feather="x"></span></button>' +
                '    </div>' +
                '</div>';
            $(this).before(newitem);
            feather.replace();
            $(this).prev().find("button").click(removeOption);
        }

        var removeOption = function () {
            var row = $(this).parent().parent();
            var num = row.find("input").attr("id").replace("Options_", "").replace("__Id", "");
            $(".option-row").each(function () {
                var currNum = $(this).find("input").attr("id").replace("Options_", "").replace("__Id", "");
                if (parseInt(currNum) > parseInt(num)) {
                    $(this).find("input").each(function () {
                        var currIdAttr = $(this).attr("id");
                        var currNameAttr = $(this).attr("name");
                        $(this).attr("id", currIdAttr.replace(currNum, parseInt(currNum) - 1));
                        $(this).attr("name", currNameAttr.replace(currNum, parseInt(currNum) - 1));
                    });
                    $(this).find("label").each(function () {
                        var currForAttr = $(this).attr("for");
                        $(this).attr("for", currForAttr.replace(currNum, parseInt(currNum) - 1));
                    });
                    $(this).find("b").each(function () {
                        console.log($(this).text());
                        $(this).text(parseInt($(this).text()) - 1);
                    });
                }
            });
            row.remove();
        }

        $('#add-option-button').click(addOption);
        $('.remove-option-button').click(removeOption);
    });
</script>
}

Covenant/Views/GruntTask/Index.cshtml
@using Covenant.Models.Grunts
@model IEnumerable<GruntTask>
@{
    Layout = "_GruntTaskLayout";
    ViewData["Title"] = "GruntTasks";
    IEnumerable<ReferenceSourceLibrary> ReferenceSourceLibraries = ViewBag.ReferenceSourceLibraries;
    IEnumerable<ReferenceAssembly> ReferenceAssemblies = ViewBag.ReferenceAssemblies;
    IEnumerable<EmbeddedResource> EmbeddedResources = ViewBag.EmbeddedResources;
}
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3">
    <h1 class="h2">Tasks</h1>
</div>

<ul class="nav nav-tabs mb-3" id="grunt-tab" role="tablist">
    <li class="nav-item">
        <a class="nav-link active" id="tasks-tab" data-toggle="tab" href="#tasks" role="tab" aria-controls="tasks" aria-selected="true">Tasks</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="libraries-tab" data-toggle="tab" href="#libraries" role="tab" aria-controls="libraries" aria-selected="false">Reference Source Libraries</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="assemblies-tab" data-toggle="tab" href="#assemblies" role="tab" aria-controls="assemblies" aria-selected="false">Reference Assemblies</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="resources-tab" data-toggle="tab" href="#resources" role="tab" aria-controls="resources" aria-selected="false">Embedded Resources</a>
    </li>
</ul>

<div class="tab-content" id="grunt-tab-content">
    <div class="tab-pane fade" id="tasks" role="tabpanel" aria-labelledby="tasks-tab">
        @{
            await Html.RenderPartialAsync("_GruntTaskTable", Model);
        }
    </div>
    <div class="tab-pane fade" id="libraries" role="tabpanel" aria-labelledby="libraries-tab">
        @{
            await Html.RenderPartialAsync("../ReferenceSourceLibrary/_ReferenceSourceLibraryTable", ReferenceSourceLibraries);
        }
    </div>
    <div class="tab-pane fade" id="assemblies" role="tabpanel" aria-labelledby="assemblies-tab">
        @{
            await Html.RenderPartialAsync("../ReferenceAssembly/_ReferenceAssemblyTable", ReferenceAssemblies);
        }
    </div>
    <div class="tab-pane fade" id="resources" role="tabpanel" aria-labelledby="resources-tab">
        @{
            await Html.RenderPartialAsync("../EmbeddedResource/_EmbeddedResourceTable", EmbeddedResources);
        }
    </div>
</div>

@section Scripts {
<script type="text/javascript">$(document).ready(function () {
        $('#task-table').DataTable({
            "pageLength": 50,
            "info": false
        });
        $('#library-table').DataTable({
            "pageLength": 50,
            "info": false
        });
        $('#assembly-table').DataTable({
            "pageLength": 50,
            "info": false
        });
        $('#resource-table').DataTable({
            "pageLength": 50,
            "info": false
        });
        $("#tasks-tab").tab('show');
    });</script>
}

Covenant/Views/GruntTask/_GruntTaskTable.cshtml
@using Covenant.Models.Grunts
@model IEnumerable<GruntTask>

<div class="table-responsive">
    <table id="task-table" class="table table-hover">
        <thead>
            <tr>
                <th>@Html.DisplayNameFor(model => model.Name)</th>
                <th>@Html.DisplayNameFor(model => model.Description)</th>
                <th>@Html.DisplayNameFor(model => model.ReferenceSourceLibraries)</th>
                <th>@Html.DisplayNameFor(model => model.ReferenceAssemblies)</th>
                <th>@Html.DisplayNameFor(model => model.EmbeddedResources)</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        <a asp-controller="GruntTask" asp-action="Edit" asp-route-id="@item.Id">
                            @Html.DisplayFor(modelItem => item.Name)
                        </a>
                    </td>
                    <td>@Html.DisplayFor(modelItem => item.Description)</td>
                    @{
                        var libraries = string.Join(",", item.ReferenceSourceLibraries.Select(RSL => RSL.Name));
                        var assemblies = string.Join(",", item.ReferenceAssemblies.Select(RA => RA.Name));
                        var resources = string.Join(",", item.EmbeddedResources.Select(ER => ER.Name));
                    }
                    <td>@Html.DisplayFor(modelItem => libraries)</td>
                    <td>@Html.DisplayFor(modelItem => assemblies)</td>
                    <td>@Html.DisplayFor(modelItem => resources)</td>
                </tr>
            }
        </tbody>
    </table>
</div>
<a asp-controller="GruntTask" asp-action="Create" class="btn btn-primary">
    <span data-feather="plus"></span>
    Create
</a>