Covenant/Models/Listeners/BridgeListener.cs
// Author: Ryan Cobb (@cobbr_io)
// Project: Covenant (https://github.com/cobbr/Covenant)
// License: GNU GPLv3

using System;
using System.IO;
using System.Net;
using System.Linq;
using System.Net.Sockets;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;

using Covenant.Core;

namespace Covenant.Models.Listeners
{
    public class BridgeListener : Listener
    {
        public bool IsBridgeConnected { get; set; }

        public string ImplantReadCode { get; set; }
        public string ImplantWriteCode { get; set; }

        private InternalListener InternalListener { get; set; }
        private readonly HashSet<string> _guids = new HashSet<string>();

        public BridgeListener()
        {
            this.Description = "A Bridge for custom listeners.";
            this.BindPort = 7444;
            this.ConnectPort = 7445;
            this.IsBridgeConnected = false;
            try
            {
				this.ConnectAddresses = new List<string>
				{
					Dns.GetHostAddresses(Dns.GetHostName())
						.FirstOrDefault(A => A.AddressFamily == AddressFamily.InterNetwork)
						.ToString()
				};
            }
            catch (SocketException) { }
        }

        public BridgeListener(int ListenerTypeId, int ProfileId) : this()
        {
            this.ListenerTypeId = ListenerTypeId;
            this.ProfileId = ProfileId;
        }

        public override CancellationTokenSource Start()
        {
            this.InternalListener = new InternalListener();
            _ = this.InternalListener.Configure(InternalListener.ToProfile(this.Profile), this.GUID, this.CovenantToken);
            CancellationTokenSource cancellationTokenSource = new CancellationTokenSource();
            Task.Run(() => this.Run(cancellationTokenSource.Token));
            return cancellationTokenSource;
        }

        public override void Stop(CancellationTokenSource cancellationTokenSource)
        {
            cancellationTokenSource.Cancel();
        }

        private async Task Run(CancellationToken token)
        {
            CancellationTokenSource clientSource = null;
            TcpListener listener = new TcpListener(IPAddress.Parse(this.BindAddress), this.BindPort);
            listener.Start();
            while (!token.IsCancellationRequested)
            {
                TcpClient client = await listener.AcceptTcpClientAsync();
                client.ReceiveTimeout = 0;
                client.SendTimeout = 0;
                if (clientSource != null)
                {
                    clientSource.Cancel();
                    clientSource.Dispose();
                }
                clientSource = new CancellationTokenSource();
                this.IsBridgeConnected = true;
                _ = Task.Run(async () => await RunClient(client, clientSource.Token), clientSource.Token);
            }
            clientSource.Cancel();
            clientSource.Dispose();
        }

        private async Task RunClient(TcpClient client, CancellationToken token)
        {
            NetworkStream stream = client.GetStream();
            stream.ReadTimeout = Timeout.Infinite;
            stream.WriteTimeout = Timeout.Infinite;
            this.InternalListener.OnNewMessage += (sender, e) =>
            {
                _ = Task.Run(async () =>
                {
                    while (!token.IsCancellationRequested)
                    {
                        try
                        {
                            string data = await this.InternalListener.Read(e.Guid);
                            this.IsBridgeConnected = true;
                            if (!string.IsNullOrEmpty(data))
                            {
                                string formatted = string.Format(((BridgeProfile)this.Profile).ReadFormat.Replace("{DATA}", "{0}").Replace("{GUID}", "{1}"), data, e.Guid);
                                this.NetworkWriteString(stream, formatted);
                            }
                            return;
                        }
                        catch (ControllerNotFoundException ex)
                        {
                            this.NetworkWriteString(stream, ex.Message);
                            return;
                        }
                        catch (Exception) { Thread.Sleep(5000); this.IsBridgeConnected = false; }
                    }
                });
            };
            while (!token.IsCancellationRequested)
            {
                string data = NetworkReadString(stream, token);
                if (data == null)
                {
                    return;
                }
                else
                {
                    List<string> parsed = data.ParseExact(((BridgeProfile)this.Profile).WriteFormat.Replace("{DATA}", "{0}").Replace("{GUID}", "{1}")).ToList();
                    if (parsed.Count == 2)
                    {
                        _guids.Add(parsed[1]);
                        await this.InternalListener.Write(parsed[1], parsed[0]);
                    }
                }
            }
        }

        private void NetworkWriteString(NetworkStream stream, string data)
        {
            if (!string.IsNullOrEmpty(data))
            {
                byte[] dataBytes = Common.CovenantEncoding.GetBytes(data);
                byte[] size = new byte[4];
                size[0] = (byte)(dataBytes.Length >> 24);
                size[1] = (byte)(dataBytes.Length >> 16);
                size[2] = (byte)(dataBytes.Length >> 8);
                size[3] = (byte)dataBytes.Length;
                stream.Write(size);
                int writtenBytes = 0;
                while (writtenBytes < dataBytes.Length)
                {
                    int bytesToWrite = Math.Min(dataBytes.Length - writtenBytes, 1024);
                    stream.Write(dataBytes, writtenBytes, bytesToWrite);
                    writtenBytes += bytesToWrite;
                }
            }
        }

        private string NetworkReadString(NetworkStream stream, CancellationToken token)
        {
            byte[] size = new byte[4];
            int totalReadBytes = 0;
            int readBytes;
            do
            {
                readBytes = stream.Read(size, totalReadBytes, size.Length - totalReadBytes);
                if (readBytes == 0) { return null; }
                totalReadBytes += readBytes;
            } while (totalReadBytes < size.Length);
            int len = (size[0] << 24) + (size[1] << 16) + (size[2] << 8) + size[3];
            byte[] buffer = new byte[1024];
            using (var ms = new MemoryStream())
            {
                totalReadBytes = 0;
                readBytes = 0;
                do
                {
                    readBytes = stream.Read(buffer, 0, buffer.Length);
                    if (readBytes == 0) { return null; }
                    ms.Write(buffer, 0, readBytes);
                    totalReadBytes += readBytes;
                } while (totalReadBytes < len);
                return Common.CovenantEncoding.GetString(ms.ToArray());
            }
        }
    }
}

Covenant/Models/Listeners/Listener.cs
// Author: Ryan Cobb (@cobbr_io)
// Project: Covenant (https://github.com/cobbr/Covenant)
// License: GNU GPLv3

using System;
using System.IO;
using System.Linq;
using System.Threading;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

using Newtonsoft.Json;

using Covenant.Core;
using Covenant.Models.Grunts;

namespace Covenant.Models.Listeners
{
    public class ListenerType
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }

        private List<ListenerTypeImplantTemplate> ListenerTypeImplantTemplates { get; set; } = new List<ListenerTypeImplantTemplate>();
        [NotMapped]
        public List<ImplantTemplate> CompatibleImplantTemplates => ListenerTypeImplantTemplates.Select(l => l.ImplantTemplate).ToList();

        [JsonIgnore]
        public List<Listener> Listeners { get; set; }
    }

    public enum ListenerStatus
    {
        Uninitialized,
        Active,
        Stopped
    }

    public class Listener
    {
        [Key]
        public int Id { get; set; }
        [Required, StringLength(100)]
        public string Name { get; set; } = Utilities.CreateShortGuid();
        [Required, StringLength(100), RegularExpression("^[a-zA-Z0-9]*$")]
        public string GUID { get; set; } = Utilities.CreateShortGuid();
        [Required]
        public string Description { get; set; } = "A generic listener.";
        [Required, RegularExpression(@"^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$", ErrorMessage = "The field BindAddress must be an IPv4 Address.")]
        public string BindAddress { get; set; } = "0.0.0.0";
        [Required, Range(1, 65535)]
        public int BindPort { get; set; } = 80;
        [Required]
        public List<string> ConnectAddresses { get; set; }
        [Required, Range(1, 65535)]
        public int ConnectPort { get; set; } = 80;
        [Required]
        public int ProfileId { get; set; }
        public Profile Profile { get; set; }

        [Required]
        public int ListenerTypeId { get; set; }
        public ListenerType ListenerType { get; set; }

        [Required]
        public ListenerStatus Status { get; set; } = ListenerStatus.Uninitialized;
        public string CovenantToken { get; set; }

        public DateTime StartTime { get; set; } = DateTime.MinValue;

        public virtual CancellationTokenSource Start() { return null; }
        public virtual void Stop(CancellationTokenSource cancellationTokenSource) { }

        protected string ListenerDirectory { get { return Common.CovenantListenersDirectory + this.GUID + Path.DirectorySeparatorChar; } }
    }

    public class ListenerStartException : Exception
    {
        public ListenerStartException(string message) : base(message) { }
    }
}

Covenant/Controllers/ViewControllers/ListenerController.cs
using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using System.Collections.Concurrent;

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Extensions.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.SignalR;

using Covenant.Core;
using Covenant.Hubs;
using Covenant.Models;
using Covenant.Models.Covenant;
using Covenant.Models.Listeners;

namespace Covenant.Controllers
{
    [Authorize]
    public class ListenerController : Controller
    {
        private readonly CovenantContext _context;
        private readonly UserManager<CovenantUser> _userManager;
        private readonly IConfiguration _configuration;
        private readonly ConcurrentDictionary<int, CancellationTokenSource> _ListenerCancellationTokens;
        private readonly IHubContext<EventHub> _eventhub;

        public ListenerController(CovenantContext context, UserManager<CovenantUser> userManager, IConfiguration configuration, ConcurrentDictionary<int, CancellationTokenSource> ListenerCancellationTokens, IHubContext<EventHub> eventhub)
        {
            _context = context;
            _userManager = userManager;
            _configuration = configuration;
            _ListenerCancellationTokens = ListenerCancellationTokens;
            _eventhub = eventhub;
        }

        // GET: /listener/
        public async Task<IActionResult> Index()
        {
            ViewBag.ListenerTypes = await _context.GetListenerTypes();
            ViewBag.Profiles = await _context.GetProfiles();
            return View(await _context.GetListeners());
        }

        // GET: /listener/create
        public async Task<IActionResult> Create()
        {
            try
            {
                ViewBag.Profiles = await _context.GetProfiles();
                ViewBag.ListenerTypes = await _context.GetListenerTypes();
                return View();
            }
            catch (Exception e) when (e is ControllerNotFoundException || e is ControllerBadRequestException || e is ControllerUnauthorizedException)
            {
                ModelState.AddModelError(string.Empty, e.Message);
                return RedirectToAction(nameof(Index));
            }
        }

        // POST: /listener/createhttp
        [HttpPost]
        public async Task<IActionResult> CreateHttp(HttpListener listener)
        {
            try
            {
                listener = await _context.CreateHttpListener(_userManager, _configuration, listener, _ListenerCancellationTokens, _eventhub);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception e) when (e is ControllerNotFoundException || e is ControllerBadRequestException || e is ControllerUnauthorizedException)
            {
                ModelState.AddModelError(string.Empty, e.Message);
                ViewBag.Profiles = await _context.GetHttpProfiles();
                ViewBag.ListenerTypes = await _context.GetListenerTypes();
                return RedirectToAction(nameof(Create));
            }
        }

        // POST: /listener/createbridge
        [HttpPost]
        public async Task<IActionResult> CreateBridge(BridgeListener listener)
        {
            try
            {
                listener = await _context.CreateBridgeListener(_userManager, _configuration, listener, _ListenerCancellationTokens, _eventhub);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception e) when (e is ControllerNotFoundException || e is ControllerBadRequestException || e is ControllerUnauthorizedException)
            {
                ModelState.AddModelError(string.Empty, e.Message);
                ViewBag.Profiles = await _context.GetHttpProfiles();
                ViewBag.ListenerTypes = await _context.GetListenerTypes();
                return RedirectToAction(nameof(Create));
            }
        }

        // GET: /listener/interact/{id}
        public async Task<IActionResult> Interact(int id)
        {
            try
            {
                Listener listener = await _context.GetListener(id);
                ViewBag.Profiles = await _context.GetHttpProfiles();
                ViewBag.HostedFiles = await _context.GetHostedFiles(listener.Id);
                ViewBag.ListenerType = await _context.GetListenerType(listener.ListenerTypeId);
                return View(listener);
            }
            catch (Exception e) when (e is ControllerNotFoundException || e is ControllerBadRequestException || e is ControllerUnauthorizedException)
            {
                ModelState.AddModelError(string.Empty, e.Message);
                return RedirectToAction(nameof(Index));
            }
        }

        // GET: /listener/start/{id}
        public async Task<IActionResult> Start(int id)
        {
            Console.WriteLine("Start: " + id);
            try
            {
                Listener listener = await _context.GetListener(id);
                if (listener.Status == ListenerStatus.Active)
                {
                    return RedirectToAction(nameof(Index));
                }
                _context.Entry(listener).State = EntityState.Detached;
                listener.Status = ListenerStatus.Active;
                Console.WriteLine("EditListener");
                await _context.EditListener(listener, _ListenerCancellationTokens, _eventhub);
                return RedirectToAction(nameof(Interact), new { id = id });
            }
            catch (Exception e) when (e is ControllerNotFoundException || e is ControllerBadRequestException || e is ControllerUnauthorizedException)
            {
                ModelState.AddModelError(string.Empty, e.Message);
                return RedirectToAction(nameof(Index));
            }
        }

        // GET: /listener/stop/{id}
        public async Task<IActionResult> Stop(int id)
        {
            try
            {
                Listener listener = await _context.GetListener(id);
                if (listener.Status == ListenerStatus.Stopped)
                {
                    return RedirectToAction(nameof(Index));
                }
                _context.Entry(listener).State = EntityState.Detached;
                listener.Status = ListenerStatus.Stopped;
                await _context.EditListener(listener, _ListenerCancellationTokens, _eventhub);
                return RedirectToAction(nameof(Interact), new { id = id });
            }
            catch (Exception e) when (e is ControllerNotFoundException || e is ControllerBadRequestException || e is ControllerUnauthorizedException)
            {
                ModelState.AddModelError(string.Empty, e.Message);
                return RedirectToAction(nameof(Index));
            }
        }

        // GET: /listener/delete/{id}
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                Listener listener = await _context.GetListener(id);
                await _context.DeleteListener(listener.Id, _ListenerCancellationTokens);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception e) when (e is ControllerNotFoundException || e is ControllerBadRequestException || e is ControllerUnauthorizedException)
            {
                ModelState.AddModelError(string.Empty, e.Message);
                return RedirectToAction(nameof(Index));
            }
        }
    }
}

Covenant/Views/Listener/Create.cshtml
@using Covenant.Models.Listeners
@model Listener
@{
    Layout = "_ListenerLayout";
    ViewData["Title"] = "HTTP Listener";
    IEnumerable<Profile> Profiles = ViewBag.Profiles;
    IEnumerable<ListenerType> ListenerTypes = ViewBag.ListenerTypes;
}

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3">
    <h1 class="h2">Create Listener</h1>
</div>

<ul class="nav nav-tabs mb-3" id="listener-tab" role="tablist">
    <li class="nav-item">
        <a class="nav-link active" id="http-tab" data-toggle="tab" href="#http" role="tab" aria-controls="http" aria-selected="true">
            <span data-feather="cloud"></span>
            HttpListener
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="bridge-tab" data-toggle="tab" href="#bridge" role="tab" aria-controls="bridge" aria-selected="false">
            <span data-feather="radio"></span>
            BridgeListener
        </a>
    </li>
</ul>

<div class="tab-content" id="listener-tab-content">
    <div class="tab-pane fade" id="http" role="tabpanel" aria-labelledby="http-tab">
        @{
            await Html.RenderPartialAsync("_CreateHttpListener", new HttpListener());
        }
    </div>
    <div class="tab-pane fade" id="bridge" role="tabpanel" aria-labelledby="bridge-tab">
        @{
            await Html.RenderPartialAsync("_CreateBridgeListener", new BridgeListener());
        }
    </div>
</div>

@section Scripts {
    <script type="text/javascript">
        $(document).ready(function () {
            var addAddress = function () {
                var num = $(".address-row").length;
                var newitem = '<div class="d-flex flex-row address-row">' +
                              '    <div class="form-group col-md-4 pl-0 mt-1 mb-1">' +
                              '        <input id="ConnectAddresses_' + num + '_" name="ConnectAddresses[' + num + ']" class="form-control address">' +
                              '    </div>' +
                              '    <div class="form-group col-md-4 pl-0 mt-1 mb-1">' +
                              '        <input id="Urls_' + num + '_" name="Urls[' + num + ']" class="form-control url" readonly>' +
                              '    </div>' +
                              '    <div class="col-auto align-self-center">' +
                              '        <button type="button" class="btn btn-outline-danger btn-sm xbutton remove-connectaddress-button"><span data-feather="x"></span></button>' +
                              '    </div>' +
                              '</div>';
                $(this).before(newitem);
                feather.replace();
                $(this).prev().find("button").click(removeAddress);
                $(".address").change(setUrl);
            }

            var removeAddress = function () {
                var row = $(this).parent().parent();
                var num = row.find("input").attr("id").replace("ConnectAddresses_", "").replace("_", "");
                $(".address-row").each(function()
                {
                    var currNum = $(this).find("input").attr("id").replace("ConnectAddresses_", "").replace("_", "");
                    if (parseInt(currNum) > parseInt(num)) {
                        $(this).find("input.address").attr("id", "ConnectAddresses_" + (parseInt(currNum) - 1) + "_");
                        $(this).find("input.address").attr("name", "ConnectAddresses[" + (parseInt(currNum) - 1) + "]");
                        $(this).find("input.url").attr("id", "Urls_" + (parseInt(currNum) - 1) + "_");
                        $(this).find("input.url").attr("name", "Urls[" + (parseInt(currNum) - 1) + "]");
                    }
                });
                row.remove();
            }

            $('#submit-listener-button').click(function () {
                var filecontrol = $("input.form-control-file")[0];
                var file = filecontrol.files[0];
                if (file == undefined)
                {
                    $("#submit-listener-form").submit();
                }
                else
                {
                    var fr = new FileReader();
                    fr.onload = receivedFileBuffer;
                    fr.readAsDataURL(file);
                }
                function receivedFileBuffer() {
                    $("input.file-filler").val(fr.result.split(",").pop()).prop("disabled", false);
                    $("input.form-control-file").prop("disabled", true);
                    $("#submit-listener-form").submit();
                }
            });
            var useSSL = "False";
            function swapOptions() {
                useSSL = $("#UseSSL").children("option:selected").text();
                if (useSSL.includes("False"))
                {
                    $(".cert-div").attr("hidden", "true");
                }
                else if (useSSL.includes("True"))
                {
                    $(".cert-div").removeAttr("hidden");
                }
                setUrl();
            };
            function setUrl() {
                var connectPort = $("#ConnectPort").val();
                var protocol = "http://";
                if (useSSL.includes("True"))
                {
                    protocol = "https://"
                }
                $(".address").each(function() {
                    var connectaddress = $(this).val();
                    $($(this).parent().next().children("input")[0]).val(protocol + connectaddress + ":" + connectPort);
                });
            }

            $("#UseSSL").change(swapOptions);
            $(".address").change(setUrl);
            $("#ConnectPort").change(setUrl);

            $('#add-connectaddress-button').click(addAddress);
            $('.remove-connectaddress-button').click(removeAddress);

            $("#http-tab").tab('show');
            
            swapOptions();
            setUrl();
        });
    </script>
}

Covenant/Views/Listener/Index.cshtml
@using Covenant.Models.Listeners
@model IEnumerable<Listener>
@{
    Layout = "_ListenerLayout";
    ViewData["Title"] = "Listeners";
    IEnumerable<ListenerType> ListenerTypes = ViewBag.ListenerTypes;
    IEnumerable<Profile> Profiles = ViewBag.Profiles;
}

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3">
    <h1 class="h2">Listeners</h1>
</div>

<ul class="nav nav-tabs mb-3" id="listener-tab" role="tablist">
    <li class="nav-item">
        <a class="nav-link active" id="listeners-tab" data-toggle="tab" href="#listeners" role="tab" aria-controls="listeners" aria-selected="true">
            <span data-feather="headphones"></span>
            Listeners
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="profiles-tab" data-toggle="tab" href="#profiles" role="tab" aria-controls="profiles" aria-selected="false">
            <span data-feather="settings"></span>
            Profiles
        </a>
    </li>
</ul>

<div class="tab-content" id="listeners-tab-content">
    <div class="tab-pane fade" id="listeners" role="tabpanel" aria-labelledby="listeners-tab">
        @{
            await Html.RenderPartialAsync("_ListenerTable", Model);
        }
        <a asp-controller="Listener" asp-action="Create" class="btn btn-primary">
            <span data-feather="plus"></span>
            Create
        </a>
    </div>
    <div class="tab-pane fade" id="profiles" role="tabpanel" aria-labelledby="profiles-tab">
        @{
            await Html.RenderPartialAsync("../Profile/_ProfileTable", Profiles);
        }
    </div>
</div>

@section Scripts {
    <script type="text/javascript">
        $(document).ready(function () {
            $('#listeners-table').DataTable({
                "pageLength": 50,
                "info" : false,
                "lengthChange" : false,
                "searching" : false
            });
            $('#profiles-table').DataTable({
                "pageLength": 50,
                "info" : false,
                "lengthChange" : false,
                "searching" : false
            });
            $("#listeners-tab").tab('show');
        });
    </script>
}

Covenant/Views/Listener/Interact.cshtml
@using Covenant.Models.Listeners
@model Listener
@{
    Layout = "_ListenerLayout";
    ViewData["Title"] = "Listener";
    IEnumerable<HttpProfile> Profiles = ViewBag.Profiles;
    IEnumerable<HostedFile> HostedFiles = ViewBag.HostedFiles;
}

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3">
    <h1 class="h2">Listener: <span class="text-primary">@Html.DisplayFor(model => model.Name)</span></h1>
</div>

@if (Model.ListenerType.Name == "HTTP")
{
    HttpListener l = (HttpListener)Model;
    await Html.RenderPartialAsync("_InteractHttpListener", l);
}
else if (Model.ListenerType.Name == "Bridge")
{
    BridgeListener l = (BridgeListener)Model;
    await Html.RenderPartialAsync("_InteractBridgeListener", l);
}

@section Scripts {
    <script type="text/javascript">$(document).ready(function () {
            $("#info-tab").tab('show');
        });</script>
}

Covenant/Views/Listener/_ListenerLayout.cshtml
@{
    Layout = "_Layout";
}

@RenderBody()

@section Sheets {
    <link rel="stylesheet" href="~/dist/codemirror/lib/codemirror.css">
}

@section Scripts {
    <script src="~/dist/codemirror/lib/codemirror.js" type="text/javascript"></script>
    <script src="~/dist/codemirror/mode/clike/clike.js"></script>
    <script src="~/dist/codemirror/mode/htmlmixed/htmlmixed.js"></script>
    <script type="text/javascript">
        $(".nav-link").removeClass("active");
        $("#nav-listeners").addClass("active");
    </script>
    @RenderSection("Scripts", required: false)
}

Covenant/Views/Listener/_ListenerTable.cshtml
@using Covenant.Models.Listeners
@model IEnumerable<Listener>

<div class="table-responsive">
    <table id="listeners-table" class="table table-hover">
        <thead>
            <tr>
                <th>@Html.DisplayNameFor(model => model.Name)</th>
                <th>@Html.DisplayNameFor(model => model.ListenerType)</th>
                <th>@Html.DisplayNameFor(model => model.Status)</th>
                <th>@Html.DisplayNameFor(model => model.StartTime)</th>
                <th>@Html.DisplayNameFor(model => model.ConnectAddresses)</th>
                <th>@Html.DisplayNameFor(model => model.ConnectPort)</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                @if (item.Status != ListenerStatus.Uninitialized)
                {
                    <tr>
                        <td>
                            <a asp-controller="Listener" asp-action="interact" asp-route-id="@item.Id">
                                @Html.DisplayFor(modelItem => item.Name)
                            </a>
                        </td>
                        <td>@Html.DisplayFor(modelItem => item.ListenerType.Name)</td>
                        <td>@Html.DisplayFor(modelItem => item.Status)</td>
                        <td>@Html.DisplayFor(modelItem => item.StartTime)</td>
                        @{ var connectaddresses = string.Join(",", item.ConnectAddresses); }
                        <td>@Html.DisplayFor(modelItem => connectaddresses)</td>
                        <td>@Html.DisplayFor(modelItem => item.ConnectPort)</td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>

Covenant/Views/Listener/_ListenerTypeTable.cshtml
@using Covenant.Models.Listeners
@model  IEnumerable<ListenerType>

<div class="table-responsive">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>@Html.DisplayNameFor(model => model.Name)</th>
                <th>@Html.DisplayNameFor(model => model.Description)</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        <a asp-controller="Listener" asp-action="@item.Name">
                            @Html.DisplayFor(modelItem => item.Name)
                        </a>
                    </td>
                    <td>@Html.DisplayFor(modelItem => item.Description)</td>
                </tr>
            }
        </tbody>
    </table>
</div>