Covenant/Controllers/ViewControllers/HostedFileController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Collections.Generic;

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.StaticFiles;
using Microsoft.AspNetCore.Authorization;

using Covenant.Core;
using Covenant.Models;
using Covenant.Models.Listeners;

namespace Covenant.Controllers.ViewControllers
{
    [Authorize]
    public class HostedFileController : Controller
    {
        private readonly CovenantContext _context;

        public HostedFileController(CovenantContext context)
        {
            _context = context;
        }

        // GET: /hostedfile/create
        public IActionResult Create(int id)
        {
            try
            {
                return View(new HostedFile { ListenerId = id });
            }
            catch (Exception e) when (e is ControllerNotFoundException || e is ControllerBadRequestException || e is ControllerUnauthorizedException)
            {
                return RedirectToAction("Index", "Listener");
            }
        }

        // POST: /hostedfile/create
        [HttpPost]
        public async Task<IActionResult> Create(HostedFile file)
        {
            try
            {
                HostedFile createdFile = await _context.CreateHostedFile(file);
                return RedirectToAction("Interact", "Listener", new { Id = createdFile.Id });
            }
            catch (Exception e) when (e is ControllerNotFoundException || e is ControllerBadRequestException || e is ControllerUnauthorizedException)
            {
                ModelState.AddModelError(string.Empty, e.Message);
                return View(new HostedFile { ListenerId = file.ListenerId });
            }
        }

        // GET: /hostedfile/download
        public async Task<IActionResult> Download(int id)
        {
            try
            {
                HostedFile file = await _context.GetHostedFile(id);
                var provider = new FileExtensionContentTypeProvider();
                if (!provider.TryGetContentType(file.Path, out string contentType))
                {
                    contentType = "application/octet-stream";
                }
                return new FileContentResult(Convert.FromBase64String(file.Content), contentType);
            }
            catch (Exception e) when (e is ControllerNotFoundException || e is ControllerBadRequestException || e is ControllerUnauthorizedException)
            {
                return RedirectToAction("Index", "Listener");
            }
        }
    }
}

Covenant/Views/HostedFile/Create.cshtml
@using Covenant.Models.Listeners
@model HostedFile
@{
    Layout = "../Listener/_ListenerLayout";
}
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap pb-2 mb-3">
    <h1 class="h2">Create HostedFile</h1>
</div>

<form id="file-submit-form" asp-action="Create">
    <div asp-validation-summary="All" class="text-danger"></div>
    <input asp-for="Id" value="@Model.Id" type="hidden">
    <input asp-for="ListenerId" value="@Model.ListenerId" type="hidden">
    <div class="form-row">
        <div class="form-group col-md-4">
            <label asp-for="Path"></label>
            <input asp-for="Path" class="form-control">
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-12">
            <label asp-for="Content">File</label>
            <input asp-for="Content" type="file" class="form-control-file">
            <input id="set-content-filler" name="Content" class="form-control file-filler" type="hidden" readonly disabled>
        </div>
    </div>
    <button type="button" id="submit-file-button" class="btn btn-primary"><span data-feather="plus"></span> Create</button>
</form>

@section Scripts
{
    <script type="text/javascript">
        $('#submit-file-button').click(function () {
            var filecontrol = $("input.form-control-file")[0];
            var file = filecontrol.files[0];
            var fr = new FileReader();
            fr.onload = receivedFileBuffer;
            fr.readAsDataURL(file);

            function receivedFileBuffer() {
                $("input.file-filler").val(fr.result.split(",").pop()).prop("disabled", false);
                $("input.form-control-file").prop("disabled", true);
                $("#file-submit-form").submit();
            }
        });
    </script>
}

Covenant/Views/HostedFile/_HostedFileTable.cshtml
@using Covenant.Models.Listeners
@model IEnumerable<HostedFile>
@{
    HttpListener Listener = ViewBag.Listener;
}

<div class="table-responsive">
    <table id="hostedfile-table" class="table table-hover">
        <thead>
            <tr>
                <th>@Html.DisplayNameFor(model => model.Path)</th>
                <th>Download</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Path)
                    </td>
                    <td>
                        <a asp-controller="HostedFile" asp-action="Download" asp-route-id="@item.Id" class="btn btn-primary">
                            <span data-feather="download"></span> 
                            Download
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
<a asp-controller="HostedFile" asp-action="Create" asp-route-id="@Listener.Id" class="btn btn-primary">
    <span data-feather="plus"></span>
    Create
</a>