Covenant/Controllers/ViewControllers/ReferenceSourceLibraryController.cs
using System;
using System.Threading.Tasks;
using System.Collections.Generic;

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;

using Covenant.Core;
using Covenant.Models;
using Covenant.Models.Grunts;

namespace Covenant.Controllers.ViewControllers
{
    [Authorize]
    public class ReferenceSourceLibraryController : Controller
    {
        private readonly CovenantContext _context;

        public ReferenceSourceLibraryController(CovenantContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Edit(int id)
        {
            try
            {
                ViewBag.ReferenceAssemblies = await _context.GetReferenceAssemblies();
                ViewBag.EmbeddedResources = await _context.GetEmbeddedResources();
                return View(await _context.GetReferenceSourceLibrary(id));
            }
            catch (Exception e) when (e is ControllerNotFoundException || e is ControllerBadRequestException || e is ControllerUnauthorizedException)
            {
                return RedirectToAction("Index", "GruntTask");
            }
        }

        public class ReferenceSourceLibraryModel : ReferenceSourceLibrary
        {
            public new List<int> ReferenceAssemblies { get; set; } = new List<int>();
            public new List<int> EmbeddedResources { get; set; } = new List<int>();
        }

        // POST: /referencesourcelibrary/edit
        [HttpPost]
        public async Task<IActionResult> Edit(ReferenceSourceLibraryModel libraryModel)
        {
            try
            {
                ReferenceSourceLibrary library = new ReferenceSourceLibrary
                {
                    Id = libraryModel.Id,
                    Name = libraryModel.Name,
                    Description = libraryModel.Description,
                    Location = libraryModel.Location,
                    SupportedDotNetVersions = libraryModel.SupportedDotNetVersions
                };
                libraryModel.ReferenceAssemblies.ForEach(async RA => {
                    library.Add(await _context.GetReferenceAssembly(RA));
                });
                libraryModel.EmbeddedResources.ForEach(async ER => {
                    library.Add(await _context.GetEmbeddedResource(ER));
                });
                ViewBag.ReferenceAssemblies = await _context.GetReferenceAssemblies();
                ViewBag.EmbeddedResources = await _context.GetEmbeddedResources();
                return View(await _context.EditReferenceSourceLibrary(library));
            }
            catch (Exception e) when (e is ControllerNotFoundException || e is ControllerBadRequestException || e is ControllerUnauthorizedException)
            {
                return RedirectToAction(nameof(Edit), new { id = libraryModel.Id });
            }
        }

        // GET: /referencesourcelibrary/create
        public async Task<IActionResult> Create()
        {
            try
            {
                ViewBag.ReferenceAssemblies = await _context.GetReferenceAssemblies();
                ViewBag.EmbeddedResources = await _context.GetEmbeddedResources();
                return View(new ReferenceSourceLibrary());
            }
            catch (Exception e) when (e is ControllerNotFoundException || e is ControllerBadRequestException || e is ControllerUnauthorizedException)
            {
                return RedirectToAction("Index", "GruntTask");
            }
        }

        // POST: /grunttask/create
        [HttpPost]
        public async Task<IActionResult> Create(ReferenceSourceLibraryModel libraryModel)
        {
            try
            {
                ReferenceSourceLibrary library = new ReferenceSourceLibrary
                {
                    Id = libraryModel.Id,
                    Name = libraryModel.Name,
                    Description = libraryModel.Description,
                    Location = libraryModel.Location,
                    SupportedDotNetVersions = libraryModel.SupportedDotNetVersions
                };
                libraryModel.ReferenceAssemblies.ForEach(async RA => {
                    library.Add(await _context.GetReferenceAssembly(RA));
                });
                libraryModel.EmbeddedResources.ForEach(async ER => {
                    library.Add(await _context.GetEmbeddedResource(ER));
                });
                ViewBag.ReferenceAssemblies = await _context.GetReferenceAssemblies();
                ViewBag.EmbeddedResources = await _context.GetEmbeddedResources();
                ReferenceSourceLibrary createdLibrary = await _context.CreateReferenceSourceLibrary(libraryModel);
                return RedirectToAction(nameof(Edit), new { Id = createdLibrary.Id });
            }
            catch (Exception e) when (e is ControllerNotFoundException || e is ControllerBadRequestException || e is ControllerUnauthorizedException)
            {
                ViewBag.ReferenceAssemblies = await _context.GetReferenceAssemblies();
                ViewBag.EmbeddedResources = await _context.GetEmbeddedResources();
                return View(new ReferenceSourceLibrary());
            }
        }
    }
}

Covenant/Views/ReferenceSourceLibrary/Create.cshtml
@using System.Linq
@using Covenant.Core
@using Covenant.Models.Grunts
@model ReferenceSourceLibrary
@{
    Layout = "../GruntTask/_GruntTaskLayout";
    ViewData["Title"] = "GruntTasks";
    IEnumerable<ReferenceAssembly> ReferenceAssemblies = ViewBag.ReferenceAssemblies;
    IEnumerable<EmbeddedResource> EmbeddedResources = ViewBag.EmbeddedResources;
    IEnumerable<SelectListItem> assemblySelectList = ReferenceAssemblies.Select(RA =>
    {
        Console.WriteLine(Model.ReferenceAssemblies.Select(MRA => MRA.Id).Contains(RA.Id));
        return new SelectListItem { Text = RA.Name, Value = RA.Id.ToString(), Selected = Model.ReferenceAssemblies.Select(MRA => MRA.Id).Contains(RA.Id) };
    });
    IEnumerable<SelectListItem> resourceSelectList = EmbeddedResources.Select(ER =>
    {
        return new SelectListItem { Text = ER.Name, Value = ER.Id.ToString(), Selected = Model.EmbeddedResources.Select(MER => MER.Id).Contains(ER.Id) };
    });
}
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap pb-2 mb-3">
    <h1 class="h2">Create ReferenceSourceLibrary</h1>
</div>

<form asp-action="Create">
    <div asp-validation-summary="All"></div>
    <input asp-for="Id" type="hidden">
    <div class="form-row">
        <div class="form-group col-md-4">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control">
        </div>
        <div class="form-group col-md-8">
            <label asp-for="Description"></label>
            <input asp-for="Description" class="form-control">
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-12">
            <label asp-for="Location"></label>
            <input asp-for="Location" class="form-control">
        </div>
    </div>
    <div class="form-row">
        <div class="form-group">
            <label asp-for="SupportedDotNetVersions"></label><br />
            <select asp-for="SupportedDotNetVersions" asp-items="@Html.GetEnumSelectList<Common.DotNetVersion>()" class="selectpicker show-menu-arrow" multiple data-dropup-auto="false" data-width="auto" data-live-search="true" data-selected-text-format="count > 3"></select>
        </div>
    </div>
    <div class="form-row">
        <div class="form-group">
            <label asp-for="ReferenceAssemblies"></label><br />
            <select asp-for="ReferenceAssemblies" class="selectpicker show-menu-arrow" multiple data-dropup-auto="false" data-width="auto" data-live-search="true" data-selected-text-format="count > 2">
                @foreach (var assembly in assemblySelectList)
                {
                    <option value="@assembly.Value">@assembly.Text</option>
                }
            </select>
        </div>
    </div>
    <div class="form-row">
        <div class="form-group">
            <label asp-for="EmbeddedResources"></label><br />
            <select asp-for="EmbeddedResources" class="selectpicker show-menu-arrow" multiple data-dropup-auto="false" data-width="auto" data-live-search="true" data-selected-text-format="count > 2">
                @foreach (var resource in resourceSelectList)
                {
                    <option value="@resource.Value">@resource.Text</option>
                }
            </select>
        </div>
    </div>

    <button type="submit" class="btn btn-primary"><span data-feather="plus"></span> Create</button>
</form>

@section Scripts {

}

Covenant/Views/ReferenceSourceLibrary/Edit.cshtml
@using System.Linq
@using Covenant.Core
@using Covenant.Models.Grunts
@model ReferenceSourceLibrary
@{
    Layout = "../GruntTask/_GruntTaskLayout";
    ViewData["Title"] = "GruntTasks";
    IEnumerable<ReferenceAssembly> ReferenceAssemblies = ViewBag.ReferenceAssemblies;
    IEnumerable<EmbeddedResource> EmbeddedResources = ViewBag.EmbeddedResources;
    IEnumerable<SelectListItem> assemblySelectList = ReferenceAssemblies.Select(RA => {
        return new SelectListItem { Text = RA.Name, Value = RA.Id.ToString(), Selected = Model.ReferenceAssemblies.Select(MRA => MRA.Id).Contains(RA.Id) };
    });
    IEnumerable<SelectListItem> resourceSelectList = EmbeddedResources.Select(ER => {
        return new SelectListItem { Text = ER.Name, Value = ER.Id.ToString(), Selected = Model.EmbeddedResources.Select(MER => MER.Id).Contains(ER.Id) };
    });
}
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap pb-2 mb-3">
    <h1 class="h2">ReferenceSourceLibrary: <span id="task-name" class="text-primary">@Html.DisplayFor(model => model.Name)</span></h1>
</div>

<form asp-action="Edit">
    <div asp-validation-summary="All"></div>
    <input asp-for="Id" value="@Model.Id" type="hidden">
    <div class="form-row">
        <div class="form-group col-md-4">
            <label asp-for="Name"></label>
            <input asp-for="Name" value="@Model.Name" class="form-control">
        </div>
        <div class="form-group col-md-8">
            <label asp-for="Description"></label>
            <input asp-for="Description" value="@Model.Description" class="form-control">
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-12">
            <label asp-for="Location"></label>
            <input asp-for="Location" value="@Model.Location" class="form-control">
        </div>
    </div>
    <div class="form-row">
        <div class="form-group">
            <label asp-for="SupportedDotNetVersions"></label><br />
            <select asp-for="SupportedDotNetVersions" asp-items="@Html.GetEnumSelectList<Common.DotNetVersion>()" class="selectpicker show-menu-arrow" multiple data-dropup-auto="false" data-width="auto" data-live-search="true" data-selected-text-format="count > 3"></select>
        </div>
    </div>
    <div class="form-row">
        <div class="form-group">
            <label asp-for="ReferenceAssemblies"></label><br/>
            <select asp-for="ReferenceAssemblies" class="selectpicker show-menu-arrow" multiple data-dropup-auto="false" data-width="auto" data-live-search="true" data-selected-text-format="count > 2">
                @foreach(var assembly in assemblySelectList)
                {
                    if (assembly.Selected)
                    {
                        <option selected value="@assembly.Value">@assembly.Text</option>
                    }
                    else
                    {
                        <option value="@assembly.Value">@assembly.Text</option>
                    }
                }
            </select>
        </div>
    </div>
    <div class="form-row">
        <div class="form-group">
            <label asp-for="EmbeddedResources"></label><br/>
            <select asp-for="EmbeddedResources" class="selectpicker show-menu-arrow" multiple data-dropup-auto="false" data-width="auto" data-live-search="true" data-selected-text-format="count > 2">
                @foreach(var resource in resourceSelectList)
                {
                    if (resource.Selected)
                    {
                        <option selected value="@resource.Value">@resource.Text</option>
                    }
                    else
                    {
                        <option value="@resource.Value">@resource.Text</option>
                    }
                }
            </select>
        </div>
    </div>
    
    <button type="submit" class="btn btn-primary"><span data-feather="edit"></span> Edit</button>
</form>

@section Scripts {

}

Covenant/Views/ReferenceSourceLibrary/_ReferenceSourceLibraryTable.cshtml
@using Covenant.Models.Grunts
@model IEnumerable<ReferenceSourceLibrary>

<div class="table-responsive">
    <table id="library-table" class="table table-hover">
        <thead>
            <tr>
                <th>@Html.DisplayNameFor(model => model.Name)</th>
                <th>@Html.DisplayNameFor(model => model.Description)</th>
                <th>@Html.DisplayNameFor(model => model.Location)</th>
                <th>@Html.DisplayNameFor(model => model.ReferenceAssemblies)</th>
                <th>@Html.DisplayNameFor(model => model.EmbeddedResources)</th>
                <th>@Html.DisplayNameFor(model => model.SupportedDotNetVersions)</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        <a asp-controller="ReferenceSourceLibrary" asp-action="Edit" asp-route-id="@item.Id">
                            @Html.DisplayFor(modelItem => item.Name)
                        </a>
                    </td>
                    <td>@Html.DisplayFor(modelItem => item.Description)</td>
                    <td>@Html.DisplayFor(modelItem => item.Location)</td>
                    @{
                        var assemblies = string.Join(",", item.ReferenceAssemblies.Select(RA => RA.Name));
                        var resources = string.Join(",", item.EmbeddedResources.Select(ER => ER.Name));
                        var versions = string.Join(",", item.SupportedDotNetVersions);
                    }
                    <td>@Html.DisplayFor(modelItem => assemblies)</td>
                    <td>@Html.DisplayFor(modelItem => resources)</td>
                    <td>@Html.DisplayFor(modelItem => versions)</td>
                </tr>
            }
        </tbody>
    </table>
</div>
<a asp-controller="ReferenceSourceLibrary" asp-action="Create" class="btn btn-primary">
    <span data-feather="plus"></span>
    Create
</a>